project_id = "lbvaghmqwhsawvxyiemw"


[functions.get-default-email-template]
verify_jwt = true

[functions.trigger-password-reset]
verify_jwt = false

[functions.get-booking-by-token]
verify_jwt = false

[functions.submit-booking-form]
verify_jwt = false

[functions.calculate-payment-amount]
verify_jwt = true

[functions.storage-monitor]
verify_jwt = true

[functions.magnolia-webhook]
verify_jwt = false

[functions.create-postfinance-payment-link]
verify_jwt = true

[functions.postfinance-webhook]
verify_jwt = false

[functions.check-payment-requirements]
verify_jwt = true

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-send]
verify_jwt = true

[functions.extract-invoice-amount]
verify_jwt = true

[functions.trigger-immediate-reminders]
verify_jwt = false

[functions.authorize-security-deposit]
verify_jwt = true

[functions.release-security-deposit]
verify_jwt = true

[functions.capture-security-deposit]
verify_jwt = true

[functions.generate-payment-receipt]
verify_jwt = false

[functions.generate-booking-confirmation]
verify_jwt = false

[functions.trigger-send-booking-form]
verify_jwt = true

[functions.trigger-payment-confirmation]
verify_jwt = false

[functions.process-booking-email]
verify_jwt = false

[functions.process-new-booking]
verify_jwt = true

[functions.confirm-bank-transfer-payment]
verify_jwt = true

[functions.trigger-bank-transfer-email]
verify_jwt = false

[functions.extract-tc-text]
verify_jwt = false

[functions.approve-extra-cost]
verify_jwt = false

[functions.generate-delivery-driver-link]
verify_jwt = true

[functions.send-payment-reminders]
verify_jwt = false

[functions.send-booking-confirmation-email]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false

[functions.get-booking-documents-by-token]
verify_jwt = false

[functions.trigger-security-deposit-confirmation]
verify_jwt = false

[functions.create-bank-transfer-payment]
verify_jwt = false

[functions.upload-bank-transfer-proof]
verify_jwt = false

[functions.validate-upload]
verify_jwt = false

[functions.upload-client-document]
verify_jwt = false

[functions.delete-client-document]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.delete-booking-permanent]
verify_jwt = true

[functions.get-client-portal-data]
verify_jwt = false

[functions.get-driver-portal-data]
verify_jwt = false

[functions.generate-balance-and-deposit-links]
verify_jwt = false

[functions.generate-tax-invoice-pdf]
verify_jwt = true

[functions.update-conversion-rate]
verify_jwt = true

[functions.create-payment-on-demand]
verify_jwt = false
