project_id = "lbvaghmqwhsawvxyiemw"

[functions.get-booking-by-token]
verify_jwt = false

[functions.submit-booking-form]
verify_jwt = false

[functions.storage-monitor]
verify_jwt = true

[functions.magnolia-webhook]
verify_jwt = false

[functions.gmail-booking-import]
verify_jwt = false

[functions.send-gmail]
verify_jwt = true

[functions.create-postfinance-payment-link]
verify_jwt = true

[functions.postfinance-webhook]
verify_jwt = false

[functions.check-payment-requirements]
verify_jwt = true

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-send]
verify_jwt = true

[functions.extract-invoice-amount]
verify_jwt = true
